.TH V7C1 1 "August 2026" "V7 toolchain" "User Commands"
.SH NAME
v7c1 \- V7 C compiler second pass (code generator)
.SH SYNOPSIS
.B v7c1
.I temp1 temp2 out.s
.SH DESCRIPTION
.B v7c1
reads the intermediate tree from
.I temp1
and the string file
.IR temp2 ,
and emits PDP-11 assembly on
.IR out.s .
.SH SEE ALSO
.BR v7c0 (1)
