# V7 as is self-hosted PDP-11 assembly (as11.s .. as29.s).  To assemble on a
# host, translate the .s files to C (see ../as/, which has as1.c/as2.c) or run
# the V7 assembler under simh.
all:
	@echo "as is PDP-11 assembly; see ../as/ for the C translation"
