/* generated by table2c.py -- do not edit */
#include "c1.h"

static char L1[] = "jmp\301\n";
static char L2[] = "GBjmp\243(I)\n";
static char L3[] = "jsr\360c,MA\n";
static char L4[] = "GBjsr\360c,#(I)\n";
static char L5[] = "GAjsr\360c,(I)\n";
static char L6[] = "clr\311\n";
static char L7[] = "clrf\311\n";
static char L8[] = "movC\301,I\n";
static char L9[] = "movof\301,I\n";
static char L10[] = "GBmovC\243(I),I\n";
static char L11[] = "GBmovof\243(I),I\n";
static char L12[] = "mov\301+,I+\nmov\301,I\n";
static char L13[] = "GBmov\243+2(I),I+\nmov\243(I),I\n";
static char L14[] = "GA";
static char L15[] = "movC\301',I\nM'C\301''\n";
static char L16[] = "mov\301',I\nM\302,A''\n";
static char L17[] = "GJmovC\243(J),I\nM'C\243(J)\n";
static char L18[] = "GBmovC\243(I),-(sp)\nM'C\243(I)\nmovC\250sp)+,I\n";
static char L19[] = "GJmov\243(J),I\nM\302,#(J)\n";
static char L20[] = "GBmov\243(I),-(sp)\nM\302,#(I)\nmov\250sp)+,I\n";
static char L21[] = "GAM\2441,A+\nV\301\n";
static char L22[] = "GJmov\243+2(J),I+\nmov\243(J),I\nM\2441,#+2(J)\nV\243(J)\n";
static char L23[] = "GBmov\243+2(I),-(sp)\nmov\243(I),-(sp)\nM\2441,#+2(I)\nV\243(I)\nmov\250sp)+,I\nmov\250sp)+,I+\n";
static char L24[] = "GAMP\311\n";
static char L25[] = "GAM\311\nM\311+\nV\311\n";
static char L26[] = "KAmovC\311,A\n";
static char L27[] = "KAmovfo\311,A\n";
static char L28[] = "GBKAmovf\311,#(I)\n";
static char L29[] = "GBmovC\302,#(I)\nmovC\243(I),I\n";
static char L30[] = "GBKAmovfo\311,#(I)\n";
static char L31[] = "GBKImovC\312,#(I)\nmovC\312,I\n";
static char L32[] = "KAGJmovf\311,#(J)\n";
static char L33[] = "KAGJmovfo\311,#(J)\n";
static char L34[] = "GDKAmovC\311,*(sp)+\n";
static char L35[] = "GDKAmovfo\311,*(sp)+\n";
static char L36[] = "KAmov\311+,A+\nmov\311,A\n";
static char L37[] = "KAGJmov\311+,2+#(J)\nmov\311,#(J)\n";
static char L38[] = "GDKAmov\311,*(sp)\nadd\2442,(sp)\nmov\311+,*(sp)+\n";
static char L39[] = "KAbicC\332,A'\nbisC\311,A''\n";
static char L41[] = "KCGBbicC\332,#(I)\nbisC\250sp),#(I)\nmov\250sp)+,I\n";
static char L42[] = "GA";
static char L43[] = "GAM'\311\n";
static char add1[] = "GAMD\302,I\n";
static char add2[] = "GAKJMD\242(J),I\n";
static char add3[] = "GAKIMP\312,I\n";
static char add4[] = "KDGAMD\252(sp)+,I\n";
static char add5[] = "KCGAMP\250sp)+,I\n";
static char L49[] = "GAM\302,I+\nV\311\n";
static char L50[] = "GAKIM\312,I+\nV\311\n";
static char L51[] = "GAM\302,I\nM\302+,I+\nV\311\n";
static char addl1[] = "GAKIM\312+,I+\nV\311\nM\312,I\n";
static char addl2[] = "KCGAM\250sp)+,I\nM\250sp)+,I+\nV\311\n";
static char L55[] = "GCKAxor\311,(sp)\nmov\250sp)+,I\n";
static char L57[] = "KCGAM\311,(sp)\nmov\250sp)+,I\nM\311+,(sp)\nmov\250sp)+,I+\n";
static char L58[] = "GAasr\311\n";
static char L63[] = "GATM\302,I-\n";
static char L64[] = "GATKJM\242(J),I-\n";
static char L65[] = "GATKIM\312,I-\n";
static char L66[] = "KCGATM\250sp)+,I-\n";
static char addq1[] = "M\302,A'\nmov\301'',I\n";
static char addq1a[] = "movC\301',I\nMP\302,I\nmovC\311,A''\n";
static char addq2[] = "KBM\242(I),A'\nmov\301'',I\n";
static char addq3[] = "KAM\311,A'\nmov\301'',I\n";
static char addq4[] = "KBGJM\242(I),#(J)\nmov\243(J),I\n";
static char addq4a[] = "movf\301',I\nKIMP\312,I\nmovf\311,A''\n";
static char addq5[] = "KCmovC\301',I\nMP\250sp)+,I\nmovC\311,A''\n";
static char addq6[] = "KCmovof\301',I\nMP\250sp)+,I\nmovfo\311,A''\n";
static char addq7[] = "KAGJM\311,#(J)\nmov\243(J),I\n";
static char addq8[] = "KCGBM\250sp)+,#(I)\nmov\243(I),I\n";
static char addq9[] = "GDKCmovC\2522(sp),I\nMP\250sp)+,I\nmovC\311,*(sp)+\n";
static char addq9a[] = "KCGBmovC\243(I),I\nMP\250sp)+,I\nmovC\311,#(I)\n";
static char addq10[] = "KCGBmovof\243(I),J\nMP\250sp)+,J\nmovfo\312,#(I)\nmovf\312,I\n";
static char L84[] = "M\302,A+\nV\301\nGA";
static char L85[] = "M\302+,A+\nV\301\nM\302,A\nGA";
static char L86[] = "KAM\311+,A+\nV\301\nM\311,A\nGA";
static char L87[] = "GBM\302,#+2(I)\nV\243(I)\nmov\243+2(I),I+\nmov\243(I),I\n";
static char L88[] = "GBM\302+,#+2(I)\nV\243(I)\nM\302,#(I)\nmov\243+2(I),I+\nmov\243(I),I\n";
static char L89[] = "KCGBM\250sp)+,#(I)\nM\250sp)+,#+2(I)\nV\243(I)\nmov\243+2(I),I+\nmov\243(I),I\n";
static char L97[] = "movC\301',I\nV\311-\nMP\302,I-\nmovC\311-,A''\n";
static char L98[] = "KCmovC\301',I\nV\311-\nM\250sp)+,I-\nmovC\311-,A''\n";
static char L99[] = "KCGJmovC\243(J),I\nV\311-\nM\250sp)+,I-\nmovC\311-,#(J)\n";
static char L100[] = "GDKCmovC\2522(sp),I\nV\311-\nM\250sp)+,I-\nmovC\311-,*(sp)+\n";
static char L107[] = "movC\301',I\nV\311-\nM\302,I-\nmovC\311,A''\n";
static char L108[] = "KCmovC\301',I\nV\311-\nM\250sp)+,I-\nmovC\311,A''\n";
static char L109[] = "KCGJmovC\243(J),I\nV\311-\nM\250sp)+,I-\nmovC\311,#(J)\n";
static char L110[] = "GDKCmovC\2522(sp),I\nV\311-\nM\250sp)+,I-\nmov\311,*(sp)+\n";
static char L112[] = "KCmovb\301',I\nxor\311,(sp)\nmov\250sp)+,I\nmovb\311,A''\n";
static char L113[] = "GDmovC\252(sp),-(sp)\nKAxor\311,(sp)\nmovC\250sp)+,I\nmovC\311,*(sp)+\n";
static char L114[] = "asrC\301'\nmovC\301'',I\n";
static char L115[] = "GBasrC\243(I)\nmovC\243(I),I\n";
static char L121[] = "movif\301,I\n";
static char L122[] = "GBmovif\243(I),I\n";
static char L123[] = "GAmovif\311,I\n";
static char L124[] = "GAmovfi\311,I\n";
static char L125[] = "GAsetl\nmovfi\311,-(sp)\nmov\250sp)+,I\nmov\250sp)+,I+\nseti\n";
static char L126[] = "setl\nmovif\301,I\nseti\n";
static char L127[] = "GBsetl\nmovif\243(I),I\nseti\n";
static char L128[] = "GCsetl\nmovif\250sp)+,I\nseti\n";
static char L129[] = "GI!clr\311\n";
static char L130[] = "GAmov\311,J\nclr\311\n";
static char L131[] = "GI!sxt\311\n";
static char L132[] = "GAmov\311,J\nsxt\311\n";
static char L133[] = "mov\301+,I\n";
static char L134[] = "GBmov\243+2(I),I\n";
static char L135[] = "KCGCjsr\360c,M\nadd\24410,sp\n";
static char L136[] = "KCGCjsr\360c,M\nadd\2446,sp\n";
static char L137[] = "GAmovb\311,I\n";
static char move1[] = "M'C\301\n";
static char move2[] = "GBM'C\243(I)\n";
static char move3[] = "ML\302,A\n";
static char move4[] = "KBML\242(I),A\n";
static char move5[] = "KAMC\311,A\n";
static char move6[] = "GBML\302,#(I)\n";
static char move7[] = "GBKJML\242(J),#(I)\n";
static char move8[] = "GBKIMC\312,#(I)\n";
static char move9[] = "KBGJML\242(I),#(J)\n";
static char move10[] = "KAGJMC\311,#(J)\n";
static char move11[] = "GDKBML\242(I),*(sp)+\n";
static char move12[] = "GDKAMC\311,*(sp)+\n";
static char L150[] = "KAmovfi\311,A\n";
static char L151[] = "KAGJmovfi\311,#(J)\n";
static char L152[] = "clr\301\nclr\301+\n";
static char L153[] = "GBclr\243(I)\nclr\262+#(I)\n";
static char move13a[] = "M\302,A+\nV\301\n";
static char L155[] = "KBmov\242(I),A+\nV\301\n";
static char L156[] = "KAmov\311,A+\nV\301\n";
static char L157[] = "KAsetl\nmovfi\311,A\nseti\n";
static char L158[] = "KAGJsetl\nmovfi\311,#(J)\nseti\n";
static char move13[] = "M\302,A\nM\302+,A+\nV\301\n";
static char move14[] = "KBM\242(I),A\nM\242+2(I),A+\nV\301\n";
static char move15[] = "KAM\311,A\nM\311+,A+\nV\301\n";
static char move14a[] = "GBM\302,#+2(I)\nV\243(I)\n";
static char move16a[] = "GBM\302+,#+2(I)\nV\243(I)\nM\302,#(I)\n";
static char move16[] = "KAGJM\311+,#+2(J)\nV\243(J)\nM\311,#(J)\n";
static char L165[] = "KCGBmov\250sp)+,#+2(I)\nV\243(I)\n";
static char move17[] = "KCGBM\250sp)+,#(I)\nM\250sp)+,#+2(I)\nV\243(I)\n";
static char L186[] = "GDKAM\311,*(sp)\nmov\250sp)+,I\nM\311+,2(I)\n";
static char L187[] = "";
static char L188[] = "M'C\301\n";
static char L194[] = "KBmovC\301',J\nM\242(I),J\nmovC\312,A''\n";
static char L195[] = "KAmovC\301',J\nM\311,J\nmovC\312,A''\n";
static char L198[] = "KCGBmovC\243(I),J\nM\250sp)+,J\nmovC\312,#(I)\n";
static char L207[] = "asrC\301\n";
static char L208[] = "GBasrC\243(I)\n";
static char L209[] = "aslC\301\n";
static char L210[] = "GBaslC\243(I)\n";
static char L211[] = "ash\302,A\n";
static char L212[] = "KBash\242(I),A\n";
static char L213[] = "KAash\311,A\n";
static char L214[] = "GAashc\302,I\nmov\311,A\nmov\311+,A+\n";
static char L215[] = "KCGAashc\250sp)+,I\nmov\311,A\nmov\311+,A+\n";
static char L216[] = "GDKCmov\262(sp),I\nmov\262(I),I+\nmov\250I),I\nashc\250sp)+,I\nmov\311,*(sp)\nadd\2442,(sp)\nmov\311+,*(sp)+\n";
static char L217[] = "bicC\332,A'\nbisC\302,A''\n";
static char L218[] = "KAbicC\332,A'\nbisC\311,A''\n";
static char L219[] = "GBbicC\332,#(I)\nbisC\302,#(I)\n";
static char fas1[] = "KAGJbicC\332,#(J)\nbisC\311,#(J)\n";
static char L221[] = "GBKIbicC\332,#(I)\nbisC\312,#(I)\n";
static char L222[] = "KCGBbicC\332,#(I)\nbisC\250sp)+,#(I)\n";
static char L224[] = "movof\301,I\n";
static char L226[] = "GBmovof\243(I),I\n";
static char L227[] = "GE";
static char L238[] = "tst\301\nX0tst\301+\nX1";
static char L239[] = "tst\301\nX0cmp\301+,B\nX1";
static char lcmp1[] = "M\301,B\nX0M\301+,B+\nX1";
static char L241[] = "GBtst\243(I)\nX0tst\243+2(I)\nX1";
static char L242[] = "GBtst\243(I)\nX0cmp\243+2(I),B\nX1";
static char lcmp2[] = "GBM\243(I),B\nX0M\243+2(I),B+\nX1";
static char L244[] = "GAtst\311\nX0tst\311+\nX1";
static char L245[] = "GAtst\311\nX0cmp\311+,B\nX1";
static char lcmp3[] = "GAM\311,B\nX0M\311+,B+\nX1";
static char lcmp4[] = "GBKJM\243(I),\"(J)\nX0M\243+2(I),\"+2(J)\nX1";
static char lcmp5[] = "GAKJM\311,\"(J)\nX0M\311+,\"+2(J)\nX1";
static char lcmp6[] = "GCKAmov\311,-(sp)\nmov\264(sp),I\nmov\250sp)+,2(sp)\nM\250sp)+,(sp)+\nX0M\311,I+\nX1";
static char L255[] = "/bit\2440,A\n/X0bit\302,A+\nX1";
static char L256[] = "GB/bit\2440,\"(I)\n/X0bit\302,\"+2(I)\nX1";
static char L263[] = "GA/bit\2440,I\n/X0bit\302,I+\nX1";
static char L264[] = "HA";
static char L265[] = "clrC\255(sp)\n";
static char L266[] = "mov\301,-(sp)\n";
static char L267[] = "GBmov\243(I),-(sp)\n";
static char L268[] = "mov\301+,-(sp)\nmov\301,-(sp)\n";
static char L269[] = "GCM'\250sp)\n";
static char L270[] = "GCM\302,(sp)\n";
static char L271[] = "GCKBM\242(I),(sp)\n";
static char L272[] = "GCKAM\311,(sp)\n";
static char L273[] = "GCclr\255(sp)\n";
static char L274[] = "GCsxt\255(sp)\n";
static char L275[] = "GAsetl\nmovfi\311,-(sp)\nseti\n";
static char L276[] = "GA!KI!";
static char L277[] = "KCGA!mov\250sp)+,r1\n";

static struct optab cr102[] = {
	{16, 0, 63, 0, L1},
	{127, 0, 63, 0, L2},
	{0, 0, 0, 0, 0},
};

static struct optab cr100[] = {
	{16, 0, 63, 0, L3},
	{127, 0, 63, 0, L4},
	{63, 0, 63, 0, L5},
	{0, 0, 0, 0, 0},
};

static struct optab cr106[] = {
	{4, 0, 63, 0, L6},
	{4, 4, 63, 0, L7},
	{16, 0, 63, 0, L8},
	{16, 5, 63, 0, L8},
	{16, 4, 63, 0, L9},
	{127, 0, 63, 0, L10},
	{127, 5, 63, 0, L10},
	{127, 4, 63, 0, L11},
	{16, 8, 63, 0, L12},
	{127, 8, 63, 0, L13},
	{63, 0, 63, 0, L14},
	{0, 0, 0, 0, 0},
};

static struct optab cr32[] = {
	{16, 0, 5, 0, L15},
	{16, 1, 63, 0, L16},
	{84, 0, 5, 0, L17},
	{127, 0, 5, 0, L18},
	{84, 1, 63, 0, L19},
	{127, 1, 63, 0, L20},
	{16, 8, 5, 0, L21},
	{84, 8, 5, 0, L22},
	{127, 8, 5, 0, L23},
	{0, 0, 0, 0, 0},
};

static struct optab cr37[] = {
	{63, 0, 63, 0, L24},
	{63, 4, 63, 0, L24},
	{63, 8, 63, 0, L25},
	{0, 0, 0, 0, 0},
};

static struct optab cr80[] = {
	{16, 0, 63, 0, L26},
	{16, 5, 63, 4, L26},
	{16, 4, 63, 4, L27},
	{127, 5, 16, 4, L28},
	{127, 0, 16, 1, L29},
	{127, 4, 16, 4, L30},
	{127, 0, 20, 0, L31},
	{84, 5, 63, 4, L32},
	{84, 4, 63, 4, L33},
	{127, 0, 63, 0, L34},
	{127, 5, 63, 4, L34},
	{127, 4, 63, 4, L35},
	{16, 8, 63, 8, L36},
	{84, 8, 63, 8, L37},
	{127, 8, 63, 8, L38},
	{0, 0, 0, 0, 0},
};

static struct optab cr16[] = {
	{16, 0, 63, 0, L39},
	{84, 0, 63, 0, fas1},
	{127, 0, 63, 0, L41},
	{0, 0, 0, 0, 0},
};

static struct optab cr40[] = {
	{63, 0, 4, 0, L42},
	{63, 0, 5, 0, L43},
	{63, 0, 16, 1, add1},
	{63, 4, 16, 5, add1},
	{63, 0, 84, 1, add2},
	{63, 4, 84, 5, add2},
	{63, 0, 20, 0, add3},
	{63, 4, 20, 4, add3},
	{63, 0, 127, 1, add4},
	{63, 4, 127, 5, add4},
	{63, 0, 63, 0, add5},
	{63, 4, 63, 4, add5},
	{63, 8, 8, 0, L49},
	{63, 8, 16, 9, L49},
	{63, 8, 20, 9, L50},
	{63, 8, 16, 8, L51},
	{63, 8, 20, 8, addl1},
	{63, 8, 63, 8, addl2},
	{0, 0, 0, 0, 0},
};

static struct optab cr49[] = {
	{63, 0, 20, 0, add3},
	{63, 0, 63, 0, L55},
	{63, 8, 20, 8, addl1},
	{63, 8, 63, 8, L57},
	{0, 0, 0, 0, 0},
};

static struct optab cr45[] = {
	{63, 0, 5, 0, L58},
	{0, 0, 0, 0, 0},
};

static struct optab cr42[] = {
	{63, 0, 16, 1, add1},
	{63, 4, 16, 5, add1},
	{63, 0, 84, 1, add2},
	{63, 4, 84, 5, add2},
	{63, 0, 20, 0, add3},
	{63, 4, 20, 4, add3},
	{63, 0, 63, 0, add5},
	{63, 4, 63, 4, add5},
	{0, 0, 0, 0, 0},
};

static struct optab cr43[] = {
	{63, 0, 16, 1, L63},
	{63, 0, 84, 1, L64},
	{63, 0, 20, 0, L65},
	{63, 0, 63, 0, L66},
	{63, 4, 16, 5, add1},
	{63, 4, 84, 5, add2},
	{63, 4, 20, 4, add3},
	{63, 4, 63, 4, add5},
	{0, 0, 0, 0, 0},
};

static struct optab cr70[] = {
	{16, 1, 16, 1, addq1},
	{16, 0, 16, 1, addq1a},
	{16, 5, 16, 5, addq1a},
	{16, 1, 127, 1, addq2},
	{16, 1, 63, 0, addq3},
	{84, 1, 127, 1, addq4},
	{16, 5, 20, 4, addq4a},
	{16, 0, 63, 0, addq5},
	{16, 5, 63, 4, addq5},
	{16, 4, 63, 4, addq6},
	{84, 1, 63, 0, addq7},
	{127, 1, 63, 0, addq8},
	{127, 0, 63, 0, addq9},
	{127, 5, 63, 4, addq9a},
	{127, 4, 63, 4, addq10},
	{16, 8, 8, 0, L84},
	{16, 8, 16, 8, L85},
	{16, 8, 63, 8, L86},
	{127, 8, 8, 0, L87},
	{127, 8, 16, 8, L88},
	{127, 8, 63, 8, L89},
	{0, 0, 0, 0, 0},
};

static struct optab cr72[] = {
	{16, 0, 16, 1, addq1a},
	{16, 5, 16, 5, addq1a},
	{16, 5, 20, 4, addq4a},
	{16, 0, 63, 0, addq5},
	{16, 5, 63, 4, addq5},
	{16, 4, 63, 4, addq6},
	{127, 0, 63, 0, addq9},
	{127, 5, 63, 4, addq9a},
	{127, 4, 63, 4, addq10},
	{0, 0, 0, 0, 0},
};

static struct optab cr73[] = {
	{16, 0, 16, 1, L97},
	{16, 0, 63, 0, L98},
	{84, 0, 63, 0, L99},
	{127, 0, 63, 0, L100},
	{16, 5, 16, 5, addq1a},
	{16, 5, 20, 4, addq4a},
	{16, 5, 63, 4, addq5},
	{16, 4, 63, 4, addq6},
	{127, 5, 63, 4, addq9a},
	{127, 4, 63, 4, addq10},
	{0, 0, 0, 0, 0},
};

static struct optab cr74[] = {
	{16, 0, 16, 1, L107},
	{16, 0, 63, 0, L108},
	{84, 0, 63, 0, L109},
	{127, 0, 63, 0, L110},
	{0, 0, 0, 0, 0},
};

static struct optab cr79[] = {
	{16, 1, 63, 0, addq3},
	{16, 3, 63, 0, L112},
	{127, 0, 63, 0, L113},
	{0, 0, 0, 0, 0},
};

static struct optab cr75[] = {
	{16, 0, 5, 0, L114},
	{127, 0, 5, 0, L115},
	{0, 0, 0, 0, 0},
};

static struct optab cr91[] = {
	{63, 8, 16, 1, add1},
	{63, 8, 84, 1, add2},
	{63, 8, 20, 0, add3},
	{63, 8, 127, 1, add4},
	{63, 8, 63, 0, add5},
	{0, 0, 0, 0, 0},
};

static struct optab cr51[] = {
	{16, 1, 63, 0, L121},
	{127, 1, 63, 0, L122},
	{63, 0, 63, 0, L123},
	{0, 0, 0, 0, 0},
};

static struct optab cr52[] = {
	{63, 4, 63, 0, L124},
	{0, 0, 0, 0, 0},
};

static struct optab cr56[] = {
	{63, 4, 63, 0, L125},
	{0, 0, 0, 0, 0},
};

static struct optab cr57[] = {
	{16, 8, 63, 0, L126},
	{127, 8, 63, 0, L127},
	{63, 8, 63, 0, L128},
	{0, 0, 0, 0, 0},
};

static struct optab cr58[] = {
	{20, 9, 63, 0, L129},
	{63, 9, 63, 0, L130},
	{20, 0, 63, 0, L131},
	{63, 0, 63, 0, L132},
	{0, 0, 0, 0, 0},
};

static struct optab cr59[] = {
	{16, 8, 63, 0, L133},
	{127, 8, 63, 0, L134},
	{0, 0, 0, 0, 0},
};

static struct optab cr82[] = {
	{63, 8, 63, 8, L135},
	{0, 0, 0, 0, 0},
};

static struct optab cr86[] = {
	{63, 0, 63, 8, L136},
	{0, 0, 0, 0, 0},
};

static struct optab cr109[] = {
	{63, 0, 63, 0, L137},
	{0, 0, 0, 0, 0},
};

static struct optab ci80[] = {
	{16, 0, 4, 0, move1},
	{16, 5, 4, 4, move1},
	{127, 0, 4, 0, move2},
	{127, 5, 4, 4, move2},
	{16, 0, 16, 1, move3},
	{16, 3, 16, 0, move3},
	{16, 3, 127, 0, move4},
	{16, 0, 127, 1, move4},
	{16, 0, 63, 0, move5},
	{127, 0, 16, 1, move6},
	{127, 3, 16, 0, move6},
	{127, 0, 84, 1, move7},
	{127, 3, 84, 0, move7},
	{127, 0, 20, 0, move8},
	{84, 0, 127, 1, move9},
	{84, 3, 127, 0, move9},
	{84, 0, 63, 0, move10},
	{127, 0, 127, 1, move11},
	{127, 3, 127, 0, move11},
	{127, 0, 63, 0, move12},
	{16, 1, 63, 4, L150},
	{84, 1, 63, 4, L151},
	{16, 8, 4, 0, L152},
	{127, 8, 4, 0, L153},
	{16, 8, 16, 1, move13a},
	{16, 8, 127, 1, L155},
	{16, 8, 63, 0, L156},
	{16, 8, 63, 4, L157},
	{84, 8, 63, 4, L158},
	{16, 8, 16, 8, move13},
	{16, 8, 127, 8, move14},
	{16, 8, 63, 8, move15},
	{127, 8, 16, 1, move14a},
	{127, 8, 16, 8, move16a},
	{84, 8, 63, 8, move16},
	{127, 8, 63, 0, L165},
	{127, 8, 63, 8, move17},
	{0, 0, 0, 0, 0},
};

static struct optab ci78[] = {
	{16, 0, 16, 1, move3},
	{16, 3, 16, 0, move3},
	{16, 0, 63, 0, move5},
	{127, 0, 16, 1, move6},
	{127, 3, 16, 0, move6},
	{127, 0, 84, 1, move7},
	{127, 3, 84, 0, move7},
	{127, 0, 20, 0, move8},
	{84, 0, 127, 1, move9},
	{84, 3, 127, 0, move9},
	{84, 0, 63, 0, move10},
	{127, 0, 127, 1, move11},
	{127, 3, 127, 0, move11},
	{127, 0, 63, 0, move12},
	{16, 8, 8, 0, move13a},
	{16, 8, 16, 9, move13a},
	{16, 8, 16, 8, move13},
	{16, 8, 127, 8, move14},
	{16, 8, 63, 8, move15},
	{127, 8, 8, 0, move14a},
	{127, 8, 16, 8, move16a},
	{84, 8, 63, 8, move16},
	{127, 8, 63, 8, move17},
	{0, 0, 0, 0, 0},
};

static struct optab ci79[] = {
	{16, 8, 63, 8, move15},
	{84, 8, 63, 8, move16},
	{127, 8, 63, 8, L186},
	{0, 0, 0, 0, 0},
};

static struct optab ci70[] = {
	{127, 0, 4, 0, L187},
	{16, 0, 4, 0, L187},
	{16, 0, 5, 0, L188},
	{16, 1, 16, 1, move3},
	{16, 1, 127, 1, move4},
	{16, 1, 63, 0, move5},
	{127, 0, 5, 0, move2},
	{84, 1, 127, 1, move9},
	{16, 0, 127, 1, L194},
	{16, 0, 63, 0, L195},
	{84, 1, 63, 0, move10},
	{127, 1, 63, 0, move12},
	{127, 0, 63, 0, L198},
	{16, 8, 8, 0, move13a},
	{16, 8, 16, 9, move13a},
	{16, 8, 16, 8, move13},
	{16, 8, 127, 8, move14},
	{16, 8, 63, 8, move15},
	{127, 8, 8, 0, move14a},
	{127, 8, 16, 9, move14a},
	{127, 8, 16, 8, move16a},
	{84, 8, 63, 8, move16},
	{127, 8, 63, 8, move17},
	{0, 0, 0, 0, 0},
};

static struct optab ci75[] = {
	{16, 0, 5, 0, L207},
	{127, 0, 5, 0, L208},
	{0, 0, 0, 0, 0},
};

static struct optab ci76[] = {
	{16, 0, 5, 0, L209},
	{127, 0, 5, 0, L210},
	{9, 0, 16, 1, L211},
	{9, 0, 127, 1, L212},
	{9, 0, 63, 0, L213},
	{0, 0, 0, 0, 0},
};

static struct optab cr92[] = {
	{16, 8, 16, 1, L214},
	{16, 8, 63, 0, L215},
	{127, 8, 63, 0, L216},
	{0, 0, 0, 0, 0},
};

static struct optab ci16[] = {
	{16, 0, 16, 0, L217},
	{16, 0, 63, 0, L218},
	{127, 0, 16, 0, L219},
	{84, 0, 63, 0, fas1},
	{127, 0, 20, 0, L221},
	{127, 0, 63, 0, L222},
	{0, 0, 0, 0, 0},
};

static struct optab cc60[] = {
	{16, 0, 4, 0, move1},
	{16, 5, 4, 4, move1},
	{16, 4, 4, 0, L224},
	{127, 0, 4, 0, move2},
	{127, 5, 4, 4, move2},
	{127, 4, 4, 0, L226},
	{63, 0, 4, 0, L227},
	{63, 4, 4, 4, L227},
	{16, 1, 16, 1, move3},
	{16, 3, 16, 3, move3},
	{127, 1, 16, 1, move6},
	{127, 3, 16, 3, move6},
	{63, 0, 16, 1, add1},
	{63, 4, 16, 5, add1},
	{127, 1, 84, 1, move7},
	{127, 3, 84, 3, move7},
	{127, 1, 20, 0, move8},
	{63, 0, 84, 1, add2},
	{63, 4, 84, 5, add2},
	{63, 0, 20, 0, add3},
	{63, 4, 20, 4, add3},
	{127, 1, 127, 1, move11},
	{127, 3, 127, 3, move11},
	{127, 1, 63, 0, move12},
	{63, 0, 63, 0, add5},
	{63, 4, 63, 4, add5},
	{16, 8, 4, 0, L238},
	{16, 8, 8, 0, L239},
	{16, 8, 16, 9, L239},
	{16, 8, 16, 8, lcmp1},
	{127, 8, 4, 0, L241},
	{127, 8, 8, 0, L242},
	{127, 8, 16, 9, L242},
	{127, 8, 16, 8, lcmp2},
	{63, 8, 4, 0, L244},
	{63, 8, 8, 0, L245},
	{63, 8, 16, 9, L245},
	{63, 8, 16, 8, lcmp3},
	{127, 8, 84, 8, lcmp4},
	{63, 8, 84, 8, lcmp5},
	{63, 8, 63, 8, lcmp6},
	{0, 0, 0, 0, 0},
};

static struct optab cc81[] = {
	{16, 0, 16, 0, move3},
	{127, 0, 16, 0, move6},
	{63, 0, 16, 0, add1},
	{63, 0, 20, 0, add3},
	{63, 0, 63, 0, add5},
	{16, 8, 8, 0, L255},
	{16, 8, 16, 9, L255},
	{127, 8, 8, 0, L256},
	{127, 8, 16, 9, L256},
	{16, 8, 16, 8, lcmp1},
	{127, 8, 16, 8, lcmp2},
	{63, 8, 16, 8, lcmp3},
	{127, 8, 84, 8, lcmp4},
	{63, 8, 84, 8, lcmp5},
	{63, 8, 63, 8, lcmp6},
	{63, 8, 8, 0, L263},
	{63, 8, 16, 9, L263},
	{0, 0, 0, 0, 0},
};

static struct optab rest[] = {
	{63, 0, 63, 0, L264},
	{63, 4, 63, 4, L264},
	{0, 0, 0, 0, 0},
};

static struct optab cs106[] = {
	{4, 0, 63, 0, L265},
	{4, 4, 63, 0, L265},
	{16, 1, 63, 0, L266},
	{127, 1, 63, 0, L267},
	{16, 8, 63, 0, L268},
	{0, 0, 0, 0, 0},
};

static struct optab cs40[] = {
	{16, 0, 5, 0, L269},
	{16, 0, 16, 1, L270},
	{16, 0, 127, 1, L271},
	{16, 0, 63, 0, L272},
	{0, 0, 0, 0, 0},
};

static struct optab cs58[] = {
	{63, 9, 63, 0, L273},
	{63, 0, 63, 0, L274},
	{0, 0, 0, 0, 0},
};

static struct optab cs56[] = {
	{63, 4, 63, 0, L275},
	{0, 0, 0, 0, 0},
};

static struct optab ci116[] = {
	{63, 0, 20, 0, L276},
	{63, 0, 63, 0, L277},
	{0, 0, 0, 0, 0},
};

struct table regtab[] = {
	{106, cr106},
	{30, cr70},
	{31, cr70},
	{32, cr32},
	{33, cr32},
	{37, cr37},
	{38, cr37},
	{98, cr100},
	{99, cr100},
	{80, cr80},
	{40, cr40},
	{41, cr40},
	{42, cr42},
	{43, cr43},
	{14, cr43},
	{44, cr43},
	{45, cr45},
	{46, cr40},
	{55, cr40},
	{48, cr40},
	{49, cr49},
	{70, cr70},
	{71, cr70},
	{72, cr72},
	{73, cr73},
	{74, cr74},
	{75, cr75},
	{76, cr72},
	{78, cr70},
	{85, cr70},
	{79, cr79},
	{102, cr102},
	{51, cr51},
	{52, cr52},
	{56, cr56},
	{57, cr57},
	{58, cr58},
	{59, cr59},
	{91, cr91},
	{82, cr82},
	{83, cr82},
	{84, cr82},
	{86, cr86},
	{87, cr86},
	{88, cr86},
	{16, cr16},
	{92, cr92},
	{17, cr43},
	{18, cr74},
	{109, cr109},
	{0, 0},
};

struct table efftab[] = {
	{30, ci70},
	{31, ci70},
	{32, ci70},
	{33, ci70},
	{80, ci80},
	{70, ci70},
	{71, ci70},
	{78, ci78},
	{79, ci79},
	{85, ci78},
	{75, ci75},
	{76, ci76},
	{16, ci16},
	{116, ci116},
	{0, 0},
};

struct table cctab[] = {
	{106, cc60},
	{28, rest},
	{55, rest},
	{34, rest},
	{35, rest},
	{36, rest},
	{37, rest},
	{40, rest},
	{41, rest},
	{42, rest},
	{43, rest},
	{81, cc81},
	{48, rest},
	{60, cc60},
	{61, cc60},
	{62, cc60},
	{63, cc60},
	{64, cc60},
	{65, cc60},
	{66, cc60},
	{67, cc60},
	{68, cc60},
	{69, cc60},
	{72, rest},
	{73, rest},
	{79, rest},
	{0, 0},
};

struct table sptab[] = {
	{106, cs106},
	{40, cs40},
	{41, cs40},
	{55, cs40},
	{48, cs40},
	{58, cs58},
	{56, cs56},
	{0, 0},
};

struct table lsptab[1];
