#!/bin/sh
#
# build-libc — build V7's /usr/src/libc into a V7-format libc.a using the
# ported toolchain.  Runs *inside* tools/v7check.sh, which provides the V7
# /usr/include and puts the ported cc/as on PATH.
#
# Two V7 scripts define the order (both from unixtree/V7/usr/src/libc/):
#   compall  — `cc -c [-O] /usr/src/libc/<dir>/<file>` per source
#   mklib    — `ar rc libc.a <member>.o ...` in the linker's search order
# We reproduce compall's order first, then archive in mklib's order.
#
set -eu

# Resolve the repo root from this script's location (lib/build-libc.sh -> ..).
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
topdir=$(CDPATH= cd -- "$here/.." && pwd -P)
SRC="$topdir/orig/usr/src/libc"
MKVAR="$topdir/tools/mkvar.py"
OUT=${1:-"$topdir/lib/libc.a"}
# Make OUT absolute now; we cd into a temp build dir next, which would break a
# relative output path.
case "$OUT" in
	/*) ;;
	*) OUT=$(pwd -P)/"$OUT" ;;
esac

BLD=$(mktemp -d "${TMPDIR:-/tmp}/libc.XXXXXX")
trap 'rm -rf "$BLD"' EXIT

cd "$BLD"
echo "build-libc: compiling V7 /usr/src/libc into $OUT"

cc -c -O "$SRC/stdio/getgrgid.c"
cc -c -O "$SRC/stdio/getgrnam.c"
cc -c -O "$SRC/stdio/getgrent.c"
cc -c -O "$SRC/stdio/getpass.c"
cc -c -O "$SRC/stdio/getpwnam.c"
cc -c -O "$SRC/stdio/getpwuid.c"
cc -c -O "$SRC/stdio/getpwent.c"
cc -c -O "$SRC/stdio/fgetc.c"
cc -c -O "$SRC/stdio/fputc.c"
cc -c -O "$SRC/stdio/getchar.c"
cc -c -O "$SRC/stdio/putchar.c"
cc -c -O "$SRC/stdio/popen.c"
cc -c -O "$SRC/stdio/freopen.c"
cc -c -O "$SRC/stdio/fgets.c"
cc -c -O "$SRC/stdio/fputs.c"
cc -c -O "$SRC/stdio/getpw.c"
cc -c -O "$SRC/stdio/fseek.c"
cc -c -O "$SRC/stdio/ftell.c"
cc -c -O "$SRC/stdio/rew.c"
cc -c -O "$SRC/stdio/rdwr.c"
cc -c -O "$SRC/stdio/system.c"
cc -c -O "$SRC/stdio/fopen.c"
cc -c -O "$SRC/stdio/fdopen.c"
cc -c -O "$SRC/stdio/scanf.c"
cc -c -O "$SRC/stdio/doscan.c"
cc -c -O "$SRC/stdio/fprintf.c"
cc -c -O "$SRC/stdio/gets.c"
cc -c -O "$SRC/stdio/getw.c"
cc -c -O "$SRC/stdio/printf.c"
cc -c -O "$SRC/stdio/puts.c"
cc -c -O "$SRC/stdio/putw.c"
cc -c -O "$SRC/stdio/sprintf.c"
cc -c -O "$SRC/stdio/ungetc.c"
cc -c -O "$SRC/stdio/filbuf.c"
cc -c -O "$SRC/stdio/setbuf.c"
cc -c "$SRC/stdio/fltpr.s"
cc -c "$SRC/stdio/doprnt.s"
cc -c -O "$SRC/stdio/gcvt.c"
cc -c "$SRC/stdio/ffltpr.s"
cc -c -O "$SRC/stdio/strout.c"
cc -c -O "$SRC/stdio/flsbuf.c"
cc -c -O "$SRC/stdio/endopen.c"
cc -c -O "$SRC/stdio/findiop.c"
cc -c -O "$SRC/stdio/clrerr.c"
cc -c -O "$SRC/stdio/data.c"
cc -c "$SRC/gen/cuexit.s"
cc -c -O "$SRC/gen/execvp.c"
cc -c -O "$SRC/gen/getenv.c"
cc -c -O "$SRC/gen/getlogin.c"
cc -c -O "$SRC/gen/perror.c"
cc -c -O "$SRC/gen/sleep.c"
cc -c -O "$SRC/gen/timezone.c"
cc -c -O "$SRC/gen/ttyslot.c"
cc -c -O "$SRC/gen/ttyname.c"
cc -c "$SRC/gen/abort.s"
cc -c -O "$SRC/gen/abs.c"
cc -c -O "$SRC/gen/atof.c"
cc -c -O "$SRC/gen/atoi.c"
cc -c -O "$SRC/gen/atol.c"
cc -c -O "$SRC/gen/crypt.c"
cc -c -O "$SRC/gen/ctime.c"
cc -c -O "$SRC/gen/calloc.c"
cc -c -O "$SRC/gen/malloc.c"
cc -c -O "$SRC/gen/ecvt.c"
cc -c -O "$SRC/gen/errlst.c"
cc -c "$SRC/gen/fakcu.s"
cc -c "$SRC/gen/fakfp.s"
cc -c "$SRC/gen/frexp11.s"
cc -c -O "$SRC/gen/isatty.c"
cc -c -O "$SRC/gen/l3.c"
cc -c "$SRC/gen/ldexp11.s"
cc -c "$SRC/gen/ldfps.s"
cc -c -O "$SRC/gen/mktemp.c"
cc -c "$SRC/gen/modf11.s"
cc -c -O "$SRC/gen/mpx.c"
cc -c -O "$SRC/gen/mon.c"
cc -c -O "$SRC/gen/nlist.c"
cc -c -O "$SRC/gen/qsort.c"
cc -c -O "$SRC/gen/rand.c"
cc -c "$SRC/gen/setjmp.s"
cc -c -O "$SRC/gen/stty.c"
cc -c -O "$SRC/gen/swab.c"
cc -c -O "$SRC/gen/tell.c"
cc -c -O "$SRC/gen/ctype_.c"
cc -c -O "$SRC/gen/index.c"
cc -c -O "$SRC/gen/rindex.c"
cc -c -O "$SRC/gen/strcat.c"
cc -c -O "$SRC/gen/strncat.c"
cc -c -O "$SRC/gen/strcmp.c"
cc -c -O "$SRC/gen/strncmp.c"
cc -c -O "$SRC/gen/strcpy.c"
cc -c -O "$SRC/gen/strncpy.c"
cc -c -O "$SRC/gen/strlen.c"
cc -c "$SRC/sys/access.s"
cc -c "$SRC/sys/acct.s"
cc -c "$SRC/sys/alarm.s"
cc -c "$SRC/sys/chdir.s"
cc -c "$SRC/sys/chroot.s"
cc -c "$SRC/sys/chmod.s"
cc -c "$SRC/sys/chown.s"
cc -c "$SRC/sys/close.s"
cc -c "$SRC/sys/creat.s"
cc -c "$SRC/sys/dup.s"
cc -c "$SRC/sys/execl.s"
cc -c "$SRC/sys/execle.s"
cc -c "$SRC/sys/execv.s"
cc -c "$SRC/sys/execve.s"
cc -c "$SRC/sys/exit.s"
cc -c "$SRC/sys/fork.s"
cc -c "$SRC/sys/fstat.s"
cc -c "$SRC/sys/getgid.s"
cc -c "$SRC/sys/getpid.s"
cc -c "$SRC/sys/getuid.s"
cc -c "$SRC/sys/ioctl.s"
cc -c "$SRC/sys/kill.s"
cc -c "$SRC/sys/link.s"
cc -c "$SRC/sys/lock.s"
cc -c "$SRC/sys/lseek.s"
cc -c "$SRC/sys/mknod.s"
cc -c "$SRC/sys/mount.s"
cc -c "$SRC/sys/mpxcall.s"
cc -c "$SRC/sys/nice.s"
cc -c "$SRC/sys/open.s"
cc -c "$SRC/sys/pause.s"
cc -c "$SRC/sys/phys.s"
cc -c "$SRC/sys/pipe.s"
cc -c "$SRC/sys/profil.s"
cc -c "$SRC/sys/ptrace.s"
cc -c "$SRC/sys/read.s"
cc -c "$SRC/sys/sbrk.s"
cc -c "$SRC/sys/setgid.s"
cc -c "$SRC/sys/setuid.s"
cc -c "$SRC/sys/signal.s"
cc -c "$SRC/sys/stat.s"
cc -c "$SRC/sys/stime.s"
cc -c "$SRC/sys/sync.s"
cc -c "$SRC/sys/time.s"
cc -c "$SRC/sys/times.s"
cc -c "$SRC/sys/umask.s"
cc -c "$SRC/sys/umount.s"
cc -c "$SRC/sys/unlink.s"
cc -c "$SRC/sys/utime.s"
cc -c "$SRC/sys/wait.s"
cc -c "$SRC/sys/write.s"
cc -c "$SRC/crt/aldiv.s"
cc -c "$SRC/crt/almul.s"
cc -c "$SRC/crt/alrem.s"
cc -c "$SRC/crt/cerror.s"
cc -c "$SRC/crt/ldiv.s"
cc -c "$SRC/crt/lmul.s"
cc -c "$SRC/crt/lrem.s"
cc -c "$SRC/crt/mcount.s"
cc -c "$SRC/crt/csv.s"

echo "build-libc: archiving 153 members (mklib order)"
set -- "$BLD/getgrgid.o" "$BLD/getgrnam.o" "$BLD/getgrent.o" "$BLD/getpass.o" "$BLD/getpwnam.o" "$BLD/getpwuid.o" "$BLD/getpwent.o" "$BLD/timezone.o" "$BLD/fgetc.o" "$BLD/fputc.o" "$BLD/getchar.o" "$BLD/putchar.o" "$BLD/popen.o" "$BLD/freopen.o" "$BLD/fgets.o" "$BLD/fputs.o" "$BLD/getpw.o" "$BLD/fseek.o" "$BLD/ftell.o" "$BLD/rew.o" "$BLD/rdwr.o" "$BLD/system.o" "$BLD/fopen.o" "$BLD/fdopen.o" "$BLD/scanf.o" "$BLD/doscan.o" "$BLD/fprintf.o" "$BLD/gets.o" "$BLD/getw.o" "$BLD/printf.o" "$BLD/puts.o" "$BLD/putw.o" "$BLD/sprintf.o" "$BLD/ungetc.o" "$BLD/filbuf.o" "$BLD/setbuf.o" "$BLD/fltpr.o" "$BLD/doprnt.o" "$BLD/gcvt.o" "$BLD/ffltpr.o" "$BLD/strout.o" "$BLD/flsbuf.o" "$BLD/endopen.o" "$BLD/findiop.o" "$BLD/clrerr.o" "$BLD/data.o" "$BLD/cuexit.o" "$BLD/execvp.o" "$BLD/getenv.o" "$BLD/getlogin.o" "$BLD/perror.o" "$BLD/sleep.o" "$BLD/ttyslot.o" "$BLD/ttyname.o" "$BLD/abort.o" "$BLD/abs.o" "$BLD/atof.o" "$BLD/atoi.o" "$BLD/atol.o" "$BLD/crypt.o" "$BLD/ctime.o" "$BLD/calloc.o" "$BLD/malloc.o" "$BLD/ecvt.o" "$BLD/errlst.o" "$BLD/fakcu.o" "$BLD/fakfp.o" "$BLD/frexp11.o" "$BLD/isatty.o" "$BLD/l3.o" "$BLD/ldexp11.o" "$BLD/ldfps.o" "$BLD/mktemp.o" "$BLD/modf11.o" "$BLD/mon.o" "$BLD/mpx.o" "$BLD/nlist.o" "$BLD/qsort.o" "$BLD/rand.o" "$BLD/setjmp.o" "$BLD/stty.o" "$BLD/swab.o" "$BLD/tell.o" "$BLD/ctype_.o" "$BLD/index.o" "$BLD/rindex.o" "$BLD/strcat.o" "$BLD/strncat.o" "$BLD/strcmp.o" "$BLD/strncmp.o" "$BLD/strcpy.o" "$BLD/strncpy.o" "$BLD/strlen.o" "$BLD/access.o" "$BLD/acct.o" "$BLD/alarm.o" "$BLD/chdir.o" "$BLD/chroot.o" "$BLD/chmod.o" "$BLD/chown.o" "$BLD/close.o" "$BLD/creat.o" "$BLD/dup.o" "$BLD/execl.o" "$BLD/execle.o" "$BLD/execv.o" "$BLD/execve.o" "$BLD/exit.o" "$BLD/fork.o" "$BLD/fstat.o" "$BLD/getgid.o" "$BLD/getpid.o" "$BLD/getuid.o" "$BLD/ioctl.o" "$BLD/kill.o" "$BLD/link.o" "$BLD/lock.o" "$BLD/lseek.o" "$BLD/mknod.o" "$BLD/mount.o" "$BLD/mpxcall.o" "$BLD/nice.o" "$BLD/open.o" "$BLD/pause.o" "$BLD/phys.o" "$BLD/pipe.o" "$BLD/profil.o" "$BLD/ptrace.o" "$BLD/read.o" "$BLD/sbrk.o" "$BLD/setgid.o" "$BLD/setuid.o" "$BLD/signal.o" "$BLD/stat.o" "$BLD/stime.o" "$BLD/sync.o" "$BLD/time.o" "$BLD/times.o" "$BLD/umask.o" "$BLD/umount.o" "$BLD/unlink.o" "$BLD/utime.o" "$BLD/wait.o" "$BLD/write.o" "$BLD/aldiv.o" "$BLD/almul.o" "$BLD/alrem.o" "$BLD/cerror.o" "$BLD/ldiv.o" "$BLD/lmul.o" "$BLD/lrem.o" "$BLD/mcount.o" "$BLD/csv.o"
python3 "$MKVAR" "$OUT" "$@"
echo "build-libc: wrote $OUT"
